gen_bases = [
	{'name': 'Crude Bow'},
	{'name': 'Short Bow'},
	{'name': 'Long Bow'},
	{'name': 'Composite Bow'},
	{'name': 'Recurve Bow', 'implicit': ['% to Global Critical Strike Multiplier']},
	{'name': 'Bone Bow'},
	{'name': 'Royal Bow', 'implicit': ['% increased Elemental Damage with Attack Skills']},
	{'name': 'Death Bow', 'implicit': ['% increased Critical Strike Chance']},
	{'name': 'Grove Bow'},
	{'name': 'Reflex Bow', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Decurve Bow'},
	{'name': 'Compound Bow'},
	{'name': 'Sniper Bow', 'implicit': ['% to Global Critical Strike Multiplier']},
	{'name': 'Ivory Bow'},
	{'name': 'Highborn Bow', 'implicit': ['% increased Elemental Damage with Attack Skills']},
	{'name': 'Decimation Bow', 'implicit': ['% increased Critical Strike Chance']},
	{'name': 'Thicket Bow'},
	{'name': 'Steelwood Bow', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Citadel Bow'},
	{'name': 'Ranger Bow'},
	{'name': 'Assassin Bow', 'implicit': ['% to Global Critical Strike Multiplier']},
	{'name': 'Spine Bow'},
	{'name': 'Imperial Bow', 'implicit': ['% increased Elemental Damage with Attack Skills']},
	{'name': 'Harbinger Bow', 'implicit': ['% increased Critical Strike Chance']},
	{'name': 'Maraketh Bow', 'implicit': ['10% increased Movement Speed']},
	{'name': 'Nailed Fist', 'implicit': ['+3 Life gained for each Enemy hit by Attacks']},
	{'name': 'Sharktooth Claw', 'implicit': ['+6 Life gained for each Enemy hit by Attacks']},
	{'name': 'Awl', 'implicit': ['+7 Life gained for each Enemy hit by Attacks']},
	{'name': "Cat's Paw ", 'implicit': ['+8 Life gained for each Enemy hit by Attacks']},
	{'name': 'Blinder', 'implicit': ['+12 Life gained for each Enemy hit by Attacks']},
	{'name': 'Timeworn Claw', 'implicit': ['+19 Life gained for each Enemy hit by Attacks']},
	{'name': 'Sparkling Claw', 'implicit': ['+15 Life gained for each Enemy hit by Attacks']},
	{'name': 'Fright Claw', 'implicit': ['+20 Life gained for each Enemy hit by Attacks']},
	{'name': 'Double Claw', 'implicit': ['+15 Life gained for each Enemy hit by Attacks', '+6 Mana gained for each Enemy hit by Attacks']},
	{'name': 'Thresher Claw', 'implicit': ['+25 Life gained for each Enemy hit by Attacks']},
	{'name': 'Gouger', 'implicit': ['+24 Life gained for each Enemy hit by Attacks']},
	{'name': "Tiger's Paw ", 'implicit': ['1.6% of Physical Attack Damage Leeched as Life']},
	{'name': 'Gut Ripper', 'implicit': ['+44 Life gained for each Enemy hit by Attacks']},
	{'name': 'Prehistoric Claw', 'implicit': ['2% of Physical Attack Damage Leeched as Life']},
	{'name': 'Noble Claw', 'implicit': ['+40 Life gained for each Enemy hit by Attacks']},
	{'name': 'Eagle Claw', 'implicit': ['2% of Physical Attack Damage Leeched as Life']},
	{'name': 'Twin Claw', 'implicit': ['+28 Life gained for each Enemy hit by Attacks', '+10 Mana gained for each Enemy hit by Attacks']},
	{'name': 'Great White Claw', 'implicit': ['+46 Life gained for each Enemy hit by Attacks']},
	{'name': 'Throat Stabber', 'implicit': ['+40 Life gained for each Enemy hit by Attacks']},
	{'name': "Hellion's Paw ", 'implicit': ['1.6% of Physical Attack Damage Leeched as Life']},
	{'name': 'Eye Gouger', 'implicit': ['+50 Life gained for each Enemy hit by Attacks']},
	{'name': 'Vaal Claw', 'implicit': ['2% of Physical Attack Damage Leeched as Life']},
	{'name': 'Imperial Claw', 'implicit': ['+46 Life gained for each Enemy hit by Attacks']},
	{'name': 'Terror Claw', 'implicit': ['2% of Physical Attack Damage Leeched as Life']},
	{'name': 'Gemini Claw', 'implicit': ['+38 Life gained for each Enemy hit by Attacks', '+14 Mana gained for each Enemy hit by Attacks']},
	{'name': 'Glass Shank', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Skinning Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Stiletto', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Flaying Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Prong Dagger', 'implicit': ['4% Chance to Block Attack Damage']},
	{'name': 'Poignard', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Trisula', 'implicit': ['4% Chance to Block Attack Damage']},
	{'name': 'Gutting Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Ambusher', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Sai', 'implicit': ['6% Chance to Block Attack Damage']},
	{'name': 'Rusted Hatchet'},
	{'name': 'Jade Hatchet'},
	{'name': 'Boarding Axe'},
	{'name': 'Cleaver'},
	{'name': 'Broad Axe'},
	{'name': 'Arming Axe'},
	{'name': 'Decorative Axe'},
	{'name': 'Spectral Axe'},
	{'name': 'Etched Hatchet', 'implicit': ['8% increased Global Physical Damage']},
	{'name': 'Jasper Axe'},
	{'name': 'Tomahawk'},
	{'name': 'Wrist Chopper'},
	{'name': 'War Axe'},
	{'name': 'Chest Splitter'},
	{'name': 'Ceremonial Axe'},
	{'name': 'Wraith Axe'},
	{'name': 'Engraved Hatchet', 'implicit': ['8% increased Global Physical Damage']},
	{'name': 'Karui Axe'},
	{'name': 'Siege Axe'},
	{'name': 'Reaver Axe'},
	{'name': 'Butcher Axe'},
	{'name': 'Vaal Hatchet'},
	{'name': 'Royal Axe'},
	{'name': 'Infernal Axe'},
	{'name': 'Runic Hatchet', 'implicit': ['12% increased Global Physical Damage']},
	{'name': 'Driftwood Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Tribal Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Spiked Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Stone Hammer', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'War Hammer', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Bladed Mace', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Ceremonial Mace', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'Dream Mace', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Wyrm Mace', 'implicit': ['4% increased Attack Speed']},
	{'name': 'Petrified Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Barbed Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Rock Breaker', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'Battle Hammer', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Flanged Mace', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Ornate Mace', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'Phantom Mace', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Dragon Mace', 'implicit': ['4% increased Attack Speed']},
	{'name': 'Ancestral Club', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Tenderizer', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Gavel', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'Legion Hammer', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Pernach', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Auric Mace', 'implicit': ['15% reduced Enemy Stun Threshold']},
	{'name': 'Nightmare Mace', 'implicit': ['10% reduced Enemy Stun Threshold']},
	{'name': 'Behemoth Mace', 'implicit': ['6% increased Attack Speed']},
	{'name': 'Rusted Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': "Charan's Sword ", 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Copper Sword', 'implicit': ['+45 to Accuracy Rating']},
	{'name': 'Sabre', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Broad Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'War Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Ancient Sword', 'implicit': ['+165 to Accuracy Rating']},
	{'name': 'Elegant Sword', 'implicit': ['+190 to Accuracy Rating']},
	{'name': 'Dusk Blade', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Hook Sword', 'implicit': ['4% chance to Dodge Attack Hits']},
	{'name': 'Variscite Blade', 'implicit': ['+240 to Accuracy Rating']},
	{'name': 'Cutlass', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Baselard', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Battle Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Elder Sword', 'implicit': ['+330 to Accuracy Rating']},
	{'name': 'Graceful Sword', 'implicit': ['+350 to Accuracy Rating']},
	{'name': 'Twilight Blade', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Grappler', 'implicit': ['4% chance to Dodge Attack Hits']},
	{'name': 'Gemstone Sword', 'implicit': ['+400 to Accuracy Rating']},
	{'name': 'Corsair Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Gladius', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Legion Sword', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Vaal Blade', 'implicit': ['+460 to Accuracy Rating']},
	{'name': 'Eternal Sword', 'implicit': ['+475 to Accuracy Rating']},
	{'name': 'Midnight Blade', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Tiger Hook', 'implicit': ['6% chance to Dodge Attack Hits']},
	{'name': 'Carving Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Boot Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Copper Kris', 'implicit': ['50% increased Global Critical Strike Chance']},
	{'name': 'Skean', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Imp Dagger', 'implicit': ['40% increased Global Critical Strike Chance']},
	{'name': 'Butcher Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Boot Blade', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Golden Kris', 'implicit': ['50% increased Global Critical Strike Chance']},
	{'name': 'Royal Skean', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Fiend Dagger', 'implicit': ['40% increased Global Critical Strike Chance']},
	{'name': 'Slaughter Knife', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Ezomyte Dagger', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Platinum Kris', 'implicit': ['50% increased Global Critical Strike Chance']},
	{'name': 'Imperial Skean', 'implicit': ['30% increased Global Critical Strike Chance']},
	{'name': 'Demon Dagger', 'implicit': ['40% increased Global Critical Strike Chance']},
	{'name': 'Driftwood Sceptre', 'implicit': ['10% increased Elemental Damage']},
	{'name': 'Darkwood Sceptre', 'implicit': ['12% increased Elemental Damage']},
	{'name': 'Bronze Sceptre', 'implicit': ['12% increased Elemental Damage']},
	{'name': 'Quartz Sceptre', 'implicit': ['20% increased Elemental Damage']},
	{'name': 'Iron Sceptre', 'implicit': ['14% increased Elemental Damage']},
	{'name': 'Ochre Sceptre', 'implicit': ['16% increased Elemental Damage']},
	{'name': 'Ritual Sceptre', 'implicit': ['16% increased Elemental Damage']},
	{'name': 'Shadow Sceptre', 'implicit': ['22% increased Elemental Damage']},
	{'name': 'Grinning Fetish', 'implicit': ['18% increased Elemental Damage']},
	{'name': 'Horned Sceptre', 'implicit': ['Damage Penetrates 4% Elemental Resistances']},
	{'name': 'Sekhem', 'implicit': ['18% increased Elemental Damage']},
	{'name': 'Crystal Sceptre', 'implicit': ['30% increased Elemental Damage']},
	{'name': 'Lead Sceptre', 'implicit': ['22% increased Elemental Damage']},
	{'name': 'Blood Sceptre', 'implicit': ['24% increased Elemental Damage']},
	{'name': 'Royal Sceptre', 'implicit': ['24% increased Elemental Damage']},
	{'name': 'Abyssal Sceptre', 'implicit': ['30% increased Elemental Damage']},
	{'name': 'Stag Sceptre', 'implicit': ['Damage Penetrates 4% Elemental Resistances']},
	{'name': 'Karui Sceptre', 'implicit': ['26% increased Elemental Damage']},
	{'name': "Tyrant's Sekhem ", 'implicit': ['26% increased Elemental Damage']},
	{'name': 'Opal Sceptre', 'implicit': ['40% increased Elemental Damage']},
	{'name': 'Platinum Sceptre', 'implicit': ['30% increased Elemental Damage']},
	{'name': 'Vaal Sceptre', 'implicit': ['32% increased Elemental Damage']},
	{'name': 'Carnal Sceptre', 'implicit': ['32% increased Elemental Damage']},
	{'name': 'Void Sceptre', 'implicit': ['40% increased Elemental Damage']},
	{'name': 'Sambar Sceptre', 'implicit': ['Damage Penetrates 6% Elemental Resistances']},
	{'name': 'Gnarled Branch', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Primitive Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Long Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Royal Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Crescent Staff', 'implicit': ['80% increased Global Critical Strike Chance']},
	{'name': 'Woodful Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Quarterstaff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Highborn Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Moon Staff', 'implicit': ['80% increased Global Critical Strike Chance']},
	{'name': 'Primordial Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Lathi', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Imperial Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Eclipse Staff', 'implicit': ['100% increased Global Critical Strike Chance']},
	{'name': 'Rusted Spike', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Whalebone Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Battered Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Basket Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Jagged Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Antique Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Elegant Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Thorn Rapier', 'implicit': ['+35% to Global Critical Strike Multiplier']},
	{'name': 'Smallsword', 'implicit': ['15% chance to cause Bleeding on Hit']},
	{'name': 'Wyrmbone Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Burnished Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Estoc', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Serrated Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Primeval Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Fancy Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Apex Rapier', 'implicit': ['+35% to Global Critical Strike Multiplier']},
	{'name': 'Courtesan Sword', 'implicit': ['15% chance to cause Bleeding on Hit']},
	{'name': 'Dragonbone Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Tempered Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Pecoraro', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Spiraled Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Vaal Rapier', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Jewelled Foil', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Harpy Rapier', 'implicit': ['+35% to Global Critical Strike Multiplier']},
	{'name': 'Dragoon Sword', 'implicit': ['20% chance to cause Bleeding on Hit']},
	{'name': 'Stone Axe'},
	{'name': 'Jade Chopper'},
	{'name': 'Woodsplitter'},
	{'name': 'Poleaxe'},
	{'name': 'Double Axe'},
	{'name': 'Gilded Axe'},
	{'name': 'Shadow Axe'},
	{'name': 'Dagger Axe', 'implicit': ['50% increased Critical Strike Chance']},
	{'name': 'Jasper Chopper'},
	{'name': 'Timber Axe'},
	{'name': 'Headsman Axe'},
	{'name': 'Labrys'},
	{'name': 'Noble Axe'},
	{'name': 'Abyssal Axe'},
	{'name': 'Karui Chopper'},
	{'name': 'Talon Axe', 'implicit': ['50% increased Critical Strike Chance']},
	{'name': 'Ezomyte Axe'},
	{'name': 'Vaal Axe', 'implicit': ['25% chance to Maim on Hit']},
	{'name': 'Despot Axe'},
	{'name': 'Void Axe'},
	{'name': 'Fleshripper', 'implicit': ['50% increased Critical Strike Chance']},
	{'name': 'Driftwood Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Tribal Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Mallet', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Sledgehammer', 'implicit': ['45% increased Stun Duration on Enemies']},
	{'name': 'Jagged Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Brass Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Fright Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Morning Star', 'implicit': ['15% increased Area of Effect']},
	{'name': 'Totemic Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Great Mallet', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Steelhead', 'implicit': ['45% increased Stun Duration on Enemies']},
	{'name': 'Spiny Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Plated Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Dread Maul', 'implicit': ['30% increased Stun Duration on Enemies']},
	{'name': 'Solar Maul', 'implicit': ['15% increased Area of Effect']},
	{'name': 'Karui Maul', 'implicit': ['45% increased Stun Duration on Enemies']},
	{'name': 'Colossus Mallet', 'implicit': ['30% increased Area Damage']},
	{'name': 'Piledriver', 'implicit': ['20% reduced Enemy Stun Threshold']},
	{'name': 'Meatgrinder', 'implicit': ['5% chance to deal Double Damage']},
	{'name': 'Imperial Maul', 'implicit': ['10% increased Strength']},
	{'name': 'Terror Maul', 'implicit': ['25% chance to double Stun Duration']},
	{'name': 'Coronal Maul', 'implicit': ['20% increased Area of Effect']},
	{'name': 'Corroded Blade', 'implicit': ['40% increased Global Accuracy Rating']},
	{'name': 'Longsword', 'implicit': ['+60 to Accuracy Rating']},
	{'name': 'Bastard Sword', 'implicit': ['60% increased Global Accuracy Rating']},
	{'name': 'Two-Handed Sword', 'implicit': ['+120 to Accuracy Rating']},
	{'name': 'Etched Greatsword', 'implicit': ['60% increased Global Accuracy Rating']},
	{'name': 'Ornate Sword', 'implicit': ['+185 to Accuracy Rating']},
	{'name': 'Spectral Sword', 'implicit': ['45% increased Global Accuracy Rating']},
	{'name': 'Curved Blade', 'implicit': ['+40% to Global Critical Strike Multiplier']},
	{'name': 'Butcher Sword', 'implicit': ['+250 to Accuracy Rating']},
	{'name': 'Footman Sword', 'implicit': ['60% increased Global Accuracy Rating']},
	{'name': 'Highland Blade', 'implicit': ['+305 to Accuracy Rating']},
	{'name': 'Engraved Greatsword', 'implicit': ['60% increased Global Accuracy Rating']},
	{'name': 'Tiger Sword', 'implicit': ['+360 to Accuracy Rating']},
	{'name': 'Wraith Sword', 'implicit': ['45% increased Global Accuracy Rating']},
	{'name': 'Lithe Blade', 'implicit': ['+40% to Global Critical Strike Multiplier']},
	{'name': "Headman's Sword ", 'implicit': ['+400 to Accuracy Rating']},
	{'name': 'Reaver Sword', 'implicit': ['60% increased Global Accuracy Rating']},
	{'name': 'Ezomyte Blade', 'implicit': ['+25% to Global Critical Strike Multiplier']},
	{'name': 'Vaal Greatsword', 'implicit': ['+470 to Accuracy Rating']},
	{'name': 'Lion Sword', 'implicit': ['+50 to Strength and Dexterity']},
	{'name': 'Infernal Sword', 'implicit': ['30% increased Elemental Damage with Attack Skills']},
	{'name': 'Exquisite Blade', 'implicit': ['+50% to Global Critical Strike Multiplier']},
	{'name': 'Driftwood Wand', 'implicit': ['% increased Spell Damage']},
	{'name': "Goat's Horn ", 'implicit': ['% increased Spell Damage']},
	{'name': 'Carved Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Quartz Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Spiraled Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Sage Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Pagan Wand', 'implicit': ['10% increased Cast Speed']},
	{'name': "Faun's Horn ", 'implicit': ['% increased Spell Damage']},
	{'name': 'Engraved Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Crystal Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Serpent Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Omen Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Heathen Wand', 'implicit': ['10% increased Cast Speed']},
	{'name': "Demon's Horn ", 'implicit': ['% increased Spell Damage']},
	{'name': 'Imbued Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Opal Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Tornado Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Prophecy Wand', 'implicit': ['% increased Spell Damage']},
	{'name': 'Profane Wand', 'implicit': ['14% increased Cast Speed']},
	{'name': 'Convoking Wand', 'implicit': ['Can roll Minion Modifiers']},
	{'name': 'Iron Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Coiled Staff', 'implicit': ['+20% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Vile Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Military Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Serpentine Staff', 'implicit': ['+20% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Foul Staff', 'implicit': ['+18% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Ezomyte Staff', 'implicit': ['+20% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Maelström Staff', 'implicit': ['+25% Chance to Block Attack Damage while wielding a Staff']},
	{'name': 'Judgement Staff', 'implicit': ['+20% Chance to Block Spell Damage while wielding a Staff']},
	{'name': 'Plate Vest'},
	{'name': 'Shabby Jerkin'},
	{'name': 'Simple Robe'},
	{'name': 'Padded Vest'},
	{'name': 'Chainmail Vest'},
	{'name': 'Scale Vest'},
	{'name': 'Chestplate'},
	{'name': 'Chainmail Tunic'},
	{'name': 'Light Brigandine'},
	{'name': 'Oiled Vest'},
	{'name': 'Strapped Leather'},
	{'name': 'Silken Vest'},
	{'name': 'Ringmail Coat'},
	{'name': 'Scale Doublet'},
	{'name': 'Copper Plate'},
	{'name': 'Buckskin Tunic'},
	{'name': "Scholar's Robe "},
	{'name': 'Padded Jacket'},
	{'name': 'Infantry Brigandine'},
	{'name': 'Chainmail Doublet'},
	{'name': 'War Plate'},
	{'name': 'Oiled Coat'},
	{'name': 'Silken Garb'},
	{'name': 'Wild Leather'},
	{'name': "Mage's Vestment "},
	{'name': 'Full Scale Armour'},
	{'name': 'Full Leather'},
	{'name': 'Scarlet Raiment'},
	{'name': 'Full Plate'},
	{'name': 'Full Ringmail'},
	{'name': 'Arena Plate'},
	{'name': 'Sun Leather'},
	{'name': 'Full Chainmail'},
	{'name': "Soldier's Brigandine "},
	{'name': 'Silk Robe'},
	{'name': 'Waxed Garb'},
	{'name': 'Cabalist Regalia'},
	{'name': 'Lordly Plate'},
	{'name': 'Field Lamellar'},
	{'name': "Thief's Garb "},
	{'name': 'Bone Armour'},
	{'name': 'Holy Chainmail'},
	{'name': 'Bronze Plate'},
	{'name': "Sage's Robe "},
	{'name': 'Eelskin Tunic'},
	{'name': 'Wyrmscale Doublet'},
	{'name': 'Latticed Ringmail'},
	{'name': 'Quilted Jacket'},
	{'name': 'Silken Wrap'},
	{'name': 'Frontier Leather'},
	{'name': 'Battle Plate'},
	{'name': 'Hussar Brigandine'},
	{'name': 'Crusader Chainmail'},
	{'name': 'Sleek Coat'},
	{'name': 'Sun Plate'},
	{'name': "Conjurer's Vestment "},
	{'name': 'Glorious Leather'},
	{'name': 'Full Wyrmscale'},
	{'name': 'Ornate Ringmail'},
	{'name': 'Crimson Raiment'},
	{'name': 'Coronal Leather'},
	{'name': 'Colosseum Plate'},
	{'name': 'Spidersilk Robe'},
	{'name': "Commander's Brigandine "},
	{'name': 'Chain Hauberk'},
	{'name': 'Lacquered Garb'},
	{'name': 'Majestic Plate'},
	{'name': "Cutthroat's Garb "},
	{'name': 'Destroyer Regalia'},
	{'name': 'Battle Lamellar'},
	{'name': 'Devout Chainmail'},
	{'name': 'Golden Plate'},
	{'name': "Savant's Robe "},
	{'name': 'Sharkskin Tunic'},
	{'name': 'Crypt Armour'},
	{'name': 'Dragonscale Doublet'},
	{'name': 'Loricated Ringmail'},
	{'name': 'Sentinel Jacket'},
	{'name': 'Necromancer Silks'},
	{'name': 'Crusader Plate'},
	{'name': 'Destiny Leather'},
	{'name': 'Desert Brigandine'},
	{'name': 'Conquest Chainmail'},
	{'name': 'Exquisite Leather'},
	{'name': 'Varnished Coat'},
	{'name': 'Astral Plate', 'implicit': ['% to all Elemental Resistances']},
	{'name': "Occultist's Vestment ", 'implicit': ['% increased Spell Damage']},
	{'name': 'Full Dragonscale'},
	{'name': 'Elegant Ringmail'},
	{'name': 'Blood Raiment'},
	{'name': 'Gladiator Plate'},
	{'name': 'Zodiac Leather'},
	{'name': 'Widowsilk Robe'},
	{'name': "General's Brigandine "},
	{'name': "Saint's Hauberk "},
	{'name': 'Sadist Garb'},
	{'name': 'Vaal Regalia'},
	{'name': 'Glorious Plate'},
	{'name': "Assassin's Garb ", 'implicit': ['3% increased Movement Speed']},
	{'name': 'Triumphant Lamellar'},
	{'name': 'Saintly Chainmail'},
	{'name': 'Grasping Mail'},
	{'name': 'Carnal Armour', 'implicit': ['to maximum Mana']},
	{'name': 'Iron Greaves'},
	{'name': 'Wool Shoes'},
	{'name': 'Rawhide Boots'},
	{'name': 'Chain Boots'},
	{'name': 'Wrapped Boots'},
	{'name': 'Leatherscale Boots'},
	{'name': 'Steel Greaves'},
	{'name': 'Velvet Slippers'},
	{'name': 'Goathide Boots'},
	{'name': 'Ringmail Boots'},
	{'name': 'Strapped Boots'},
	{'name': 'Ironscale Boots'},
	{'name': 'Silk Slippers'},
	{'name': 'Deerskin Boots'},
	{'name': 'Plated Greaves'},
	{'name': 'Runic Greaves'},
	{'name': 'Clasped Boots'},
	{'name': 'Mesh Boots'},
	{'name': 'Bronzescale Boots'},
	{'name': 'Scholar Boots'},
	{'name': 'Reinforced Greaves'},
	{'name': 'Shackled Boots'},
	{'name': 'Nubuck Boots'},
	{'name': 'Steelscale Boots'},
	{'name': 'Riveted Boots'},
	{'name': 'Antique Greaves'},
	{'name': 'Satin Slippers'},
	{'name': 'Eelskin Boots'},
	{'name': 'Zealot Boots'},
	{'name': 'Trapper Boots'},
	{'name': 'Serpentscale Boots'},
	{'name': 'Sharkskin Boots'},
	{'name': 'Samite Slippers'},
	{'name': 'Ancient Greaves'},
	{'name': 'Ambush Boots'},
	{'name': 'Runic Sollerets'},
	{'name': 'Soldier Boots'},
	{'name': 'Wyrmscale Boots'},
	{'name': 'Conjurer Boots'},
	{'name': 'Goliath Greaves'},
	{'name': 'Shagreen Boots'},
	{'name': 'Carnal Boots'},
	{'name': 'Legion Boots'},
	{'name': 'Hydrascale Boots'},
	{'name': 'Arcanist Slippers'},
	{'name': 'Vaal Greaves'},
	{'name': 'Stealth Boots'},
	{'name': "Assassin's Boots "},
	{'name': 'Crusader Boots'},
	{'name': 'Dragonscale Boots'},
	{'name': 'Sorcerer Boots'},
	{'name': 'Titan Greaves'},
	{'name': 'Slink Boots'},
	{'name': 'Runic Sabatons'},
	{'name': 'Murder Boots'},
	{'name': 'Two-Toned Boots', 'implicit': ['% to Cold and Lightning Resistances', '% to Fire and Lightning Resistances', '% to Fire and Cold Resistances']},
	{'name': 'Fugitive Boots', 'implicit': ['% to Chaos Resistance']},
	{'name': 'Iron Gauntlets'},
	{'name': 'Wool Gloves'},
	{'name': 'Rawhide Gloves'},
	{'name': 'Fishscale Gauntlets'},
	{'name': 'Wrapped Mitts'},
	{'name': 'Chain Gloves'},
	{'name': 'Goathide Gloves'},
	{'name': 'Plated Gauntlets'},
	{'name': 'Velvet Gloves'},
	{'name': 'Ironscale Gauntlets'},
	{'name': 'Strapped Mitts'},
	{'name': 'Ringmail Gloves'},
	{'name': 'Deerskin Gloves'},
	{'name': 'Bronze Gauntlets'},
	{'name': 'Runic Gloves'},
	{'name': 'Silk Gloves'},
	{'name': 'Bronzescale Gauntlets'},
	{'name': 'Clasped Mitts'},
	{'name': 'Mesh Gloves'},
	{'name': 'Nubuck Gloves'},
	{'name': 'Steel Gauntlets'},
	{'name': 'Steelscale Gauntlets'},
	{'name': 'Embroidered Gloves'},
	{'name': 'Trapper Mitts'},
	{'name': 'Riveted Gloves'},
	{'name': 'Eelskin Gloves'},
	{'name': 'Antique Gauntlets'},
	{'name': 'Satin Gloves'},
	{'name': 'Serpentscale Gauntlets'},
	{'name': 'Zealot Gloves'},
	{'name': 'Ambush Mitts'},
	{'name': 'Sharkskin Gloves'},
	{'name': 'Samite Gloves'},
	{'name': 'Ancient Gauntlets'},
	{'name': 'Runic Gages'},
	{'name': 'Wyrmscale Gauntlets'},
	{'name': 'Carnal Mitts'},
	{'name': 'Soldier Gloves'},
	{'name': 'Goliath Gauntlets'},
	{'name': 'Shagreen Gloves'},
	{'name': 'Conjurer Gloves'},
	{'name': 'Legion Gloves'},
	{'name': "Assassin's Mitts "},
	{'name': 'Hydrascale Gauntlets'},
	{'name': 'Arcanist Gloves'},
	{'name': 'Stealth Gloves'},
	{'name': 'Vaal Gauntlets'},
	{'name': 'Crusader Gloves'},
	{'name': 'Dragonscale Gauntlets'},
	{'name': 'Murder Mitts'},
	{'name': 'Sorcerer Gloves'},
	{'name': 'Titan Gauntlets'},
	{'name': 'Runic Gauntlets'},
	{'name': 'Slink Gloves'},
	{'name': 'Spiked Gloves', 'implicit': ['% increased Melee Damage']},
	{'name': 'Gripped Gloves', 'implicit': ['% increased Projectile Attack Damage']},
	{'name': 'Fingerless Silk Gloves', 'implicit': ['% increased Spell Damage']},
	{'name': "Apothecary's Gloves ", 'implicit': ['% increased Damage over Time']},
	{'name': 'Iron Hat'},
	{'name': 'Leather Cap'},
	{'name': 'Vine Circlet'},
	{'name': 'Scare Mask'},
	{'name': 'Battered Helm'},
	{'name': 'Rusted Coif'},
	{'name': 'Cone Helmet'},
	{'name': 'Iron Circlet'},
	{'name': 'Plague Mask'},
	{'name': 'Tricorne'},
	{'name': 'Soldier Helmet'},
	{'name': 'Sallet'},
	{'name': 'Torture Cage'},
	{'name': 'Iron Mask'},
	{'name': 'Barbute Helmet'},
	{'name': 'Leather Hood'},
	{'name': 'Great Helmet'},
	{'name': 'Visored Sallet'},
	{'name': 'Runic Helm'},
	{'name': 'Tribal Circlet'},
	{'name': 'Close Helmet'},
	{'name': 'Festival Mask'},
	{'name': 'Wolf Pelt'},
	{'name': 'Crusader Helmet'},
	{'name': 'Gilded Sallet'},
	{'name': 'Bone Circlet'},
	{'name': 'Gladiator Helmet'},
	{'name': 'Golden Mask'},
	{'name': 'Secutor Helm'},
	{'name': 'Aventail Helmet'},
	{'name': 'Raven Mask'},
	{'name': 'Lunaris Circlet'},
	{'name': 'Reaver Helmet'},
	{'name': 'Hunter Hood'},
	{'name': 'Fencer Helm'},
	{'name': 'Zealot Helmet'},
	{'name': 'Callous Mask'},
	{'name': 'Noble Tricorne'},
	{'name': 'Siege Helmet'},
	{'name': 'Steel Circlet'},
	{'name': 'Runic Crest'},
	{'name': 'Lacquered Helmet'},
	{'name': 'Regicide Mask'},
	{'name': 'Great Crown'},
	{'name': 'Necromancer Circlet'},
	{'name': 'Samnite Helmet'},
	{'name': 'Ursine Pelt'},
	{'name': 'Harlequin Mask'},
	{'name': 'Fluted Bascinet'},
	{'name': 'Magistrate Crown'},
	{'name': 'Solaris Circlet'},
	{'name': 'Ezomyte Burgonet'},
	{'name': 'Silken Hood'},
	{'name': 'Vaal Mask'},
	{'name': 'Prophet Crown'},
	{'name': 'Pig-Faced Bascinet'},
	{'name': 'Sinner Tricorne'},
	{'name': 'Royal Burgonet'},
	{'name': 'Mind Cage'},
	{'name': 'Nightmare Bascinet'},
	{'name': 'Deicide Mask'},
	{'name': 'Runic Crown'},
	{'name': 'Praetor Crown'},
	{'name': 'Eternal Burgonet'},
	{'name': 'Hubris Circlet'},
	{'name': 'Lion Pelt'},
	{'name': 'Bone Helmet', 'implicit': ['Minions deal', '% increased Damage']},
	{'name': 'Splintered Tower Shield'},
	{'name': 'Goathide Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Twig Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Spiked Bundle', 'implicit': ['2% chance to Dodge Attack Hits']},
	{'name': 'Rotted Round Shield', 'implicit': ['60% increased Block Recovery']},
	{'name': 'Corroded Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Plank Kite Shield', 'implicit': ['+4% to all Elemental Resistances']},
	{'name': 'Pine Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Yew Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Rawhide Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Driftwood Spiked Shield', 'implicit': ['2% chance to Dodge Attack Hits']},
	{'name': 'Fir Round Shield', 'implicit': ['180% increased Block Recovery']},
	{'name': 'Linden Kite Shield', 'implicit': ['+4% to all Elemental Resistances']},
	{'name': 'Bone Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Painted Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Cedar Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Reinforced Kite Shield'},
	{'name': 'Alloyed Spiked Shield', 'implicit': ['2% chance to Dodge Spell Hits']},
	{'name': 'Studded Round Shield', 'implicit': ['60% increased Block Recovery']},
	{'name': 'Tarnished Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Hammered Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Copper Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Burnished Spiked Shield', 'implicit': ['4% chance to Dodge Attack Hits']},
	{'name': 'Layered Kite Shield', 'implicit': ['+8% to all Elemental Resistances']},
	{'name': 'Scarlet Round Shield'},
	{'name': 'Jingling Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'War Buckler', 'implicit': ['9% increased Movement Speed']},
	{'name': 'Reinforced Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Splendid Round Shield', 'implicit': ['120% increased Block Recovery']},
	{'name': 'Ornate Spiked Shield', 'implicit': ['4% chance to Dodge Spell Hits']},
	{'name': 'Brass Spirit Shield'},
	{'name': 'Ceremonial Kite Shield', 'implicit': ['+12% to all Elemental Resistances']},
	{'name': 'Gilded Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Painted Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Walnut Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Oak Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Redwood Spiked Shield', 'implicit': ['2% chance to Dodge Attack Hits']},
	{'name': 'Maple Round Shield', 'implicit': ['180% increased Block Recovery']},
	{'name': 'Buckskin Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Etched Kite Shield', 'implicit': ['+4% to all Elemental Resistances']},
	{'name': 'Ivory Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Enameled Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Mahogany Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Spiked Round Shield', 'implicit': ['60% increased Block Recovery']},
	{'name': 'Compound Spiked Shield', 'implicit': ['2% chance to Dodge Spell Hits']},
	{'name': 'Ancient Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Steel Kite Shield'},
	{'name': 'Corrugated Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Bronze Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Chiming Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Crimson Round Shield'},
	{'name': 'Polished Spiked Shield', 'implicit': ['4% chance to Dodge Attack Hits']},
	{'name': 'Laminated Kite Shield', 'implicit': ['+8% to all Elemental Resistances']},
	{'name': 'Battle Buckler', 'implicit': ['9% increased Movement Speed']},
	{'name': 'Girded Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Thorium Spirit Shield'},
	{'name': 'Baroque Round Shield', 'implicit': ['120% increased Block Recovery']},
	{'name': 'Sovereign Spiked Shield', 'implicit': ['4% chance to Dodge Spell Hits']},
	{'name': 'Golden Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Crested Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Angelic Kite Shield', 'implicit': ['+12% to all Elemental Resistances']},
	{'name': 'Lacewood Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Ironwood Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Shagreen Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Teak Round Shield', 'implicit': ['180% increased Block Recovery']},
	{'name': 'Alder Spiked Shield', 'implicit': ['2% chance to Dodge Attack Hits']},
	{'name': 'Branded Kite Shield', 'implicit': ['+4% to all Elemental Resistances']},
	{'name': 'Fossilised Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Lacquered Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Ebony Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Champion Kite Shield'},
	{'name': 'Ezomyte Spiked Shield', 'implicit': ['2% chance to Dodge Spell Hits']},
	{'name': 'Spiny Round Shield', 'implicit': ['60% increased Block Recovery']},
	{'name': 'Vaal Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Vaal Buckler', 'implicit': ['3% increased Movement Speed']},
	{'name': 'Ezomyte Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Harmonic Spirit Shield', 'implicit': ['% increased Spell Damage']},
	{'name': 'Mosaic Kite Shield', 'implicit': ['+8% to all Elemental Resistances']},
	{'name': 'Cardinal Round Shield'},
	{'name': 'Crusader Buckler', 'implicit': ['9% increased Movement Speed']},
	{'name': 'Mirrored Spiked Shield', 'implicit': ['4% chance to Dodge Attack Hits']},
	{'name': 'Colossal Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Titanium Spirit Shield'},
	{'name': 'Archon Kite Shield', 'implicit': ['+12% to all Elemental Resistances']},
	{'name': 'Imperial Buckler', 'implicit': ['6% increased Movement Speed']},
	{'name': 'Pinnacle Tower Shield', 'implicit': ['to maximum Life']},
	{'name': 'Elegant Round Shield', 'implicit': ['120% increased Block Recovery']},
	{'name': 'Supreme Spiked Shield', 'implicit': ['4% chance to Dodge Spell Hits']},

	{'name': 'Paua Amulet', 'implicit': ['% increased Mana Regeneration Rate']},  # Mana Regeneration Rate +(20 to 30)
	{'name': 'Coral Amulet', 'implicit': ['Regenerate', 'Life per Second']},  # Life Regeneration Rate per Minute (120 to 240)
	{'name': 'Jade Amulet', 'implicit': ['to Dexterity']},  # Additional Dexterity (20 to 30)
	{'name': 'Amber Amulet', 'implicit': ['to Strength']},  # Additional Strength (20 to 30)
	{'name': 'Lapis Amulet', 'implicit': ['to Intelligence']},  # Additional Intelligence (20 to 30)
	{'name': 'Gold Amulet', 'implicit': ['increased Rarity of Items found']},  # Base Item Found Rarity +(12 to 20)
	{'name': 'Agate Amulet', 'implicit': ['to Strength And Intelligence']},  # Additional Strength And Intelligence (16 to 24)
	{'name': 'Turquoise Amulet', 'implicit': ['to Dexterity And Intelligenc']},  # Additional Dexterity And Intelligence (16 to 24)
	{'name': 'Citrine Amulet', 'implicit': ['to Strength And Dexterity']},  # Additional Strength And Dexterity (16 to 24)
	{'name': 'Onyx Amulet', 'implicit': ['to all Attributes']},  # Additional All Attributes (10 to 16)
	{'name': 'Marble Amulet', 'implicit': ['Regenerate', '% of Life per Second']},  # Life Regeneration Rate Per Minute (72 to 96)
	{'name': 'Seaglass Amulet', 'implicit': ['faster start of Energy Shield Recharge']},  # (10-15)% faster start of energy shield recharge
	{'name': 'Blue Pearl Amulet', 'implicit': ['% increased Mana Regeneration Rate']},  # Mana Regeneration Rate +(48 to 56)

	{'name': 'Rustic Sash', 'implicit': ['% increased Global Physical Damage']},  # Physical Damage +(12 to 24)
	{'name': 'Chain Belt', 'implicit': ['to maximum Energy Shield']},  # Base Maximum Energy Shield (9 to 20)
	{'name': 'Heavy Belt', 'implicit': ['to Strength']},  # Additional Strength (25 to 35)
	{'name': 'Leather Belt', 'implicit': ['to maximum Life']},  # Base Maximum Life (25 to 40)
	{'name': 'Cloth Belt', 'implicit': ['% increased Stun and Block Recovery']},  # Base Stun Recovery +(15 to 25)
	{'name': 'Studded Belt', 'implicit': ['% increased Stun Duration on Enemies']},  # Base Stun Duration +(20 to 30)
	{'name': 'Vanguard Belt', 'implicit': ['to Armour and Evasion Rating']},  # Base Physical Damage Reduction and Evasion Rating (260 to 320)
	{'name': 'Crystal Belt', 'implicit': ['to maximum Energy Shield']},  # Base Maximum Energy Shield (60 to 80)

	{'name': 'Iron Ring', 'implicit': ['Adds 1 to 4 Physical Damage to Attacks']},  # Minimum Added Physical Damage (1), Maximum Added Physical Damage (4)
	{'name': 'Coral Ring', 'implicit': ['to maximum Life']},  # Base Maximum Life (20 to 30)
	{'name': 'Paua Ring', 'implicit': ['to maximum Mana']},  # Base Maximum Mana (20 to 25)
	{'name': 'Sapphire Ring', 'implicit': ['to Cold Resistance']},  # Base Cold Damage Resistance (20 to 30)
	{'name': 'Topaz Ring', 'implicit': ['to Lightning Resistance']},  # Base Lightning Damage Resistance (20 to 30)
	{'name': 'Ruby Ring', 'implicit': ['to Fire Resistance']},  # Base Fire Damage Resistance (20 to 30)
	{'name': 'Gold Ring', 'implicit': ['increased Rarity of Items found']},  # Base Item Found Rarity +(6 to 15)
	{'name': 'Two-Stone Ring', 'implicit': ['% to Cold and Lightning Resistances', '% to Fire and Lightning Resistances', '% to Fire and Cold Resistances']},  # Fire And Lightning Damage Resistance (12 to 16) or Cold And Lightning Damage Resistance (12 to 16) or Fire And Cold Damage Resistance (12 to 16)
	{'name': 'Diamond Ring', 'implicit': ['% increased Global Critical Strike Chance']},  # Critical Strike Chance +(20 to 30)
	{'name': 'Moonstone Ring', 'implicit': ['to maximum Energy Shield']},  # Base Maximum Energy Shield (15 to 25)
	{'name': 'Amethyst Ring', 'implicit': ['to Chaos Resistance']},  # Base Chaos Damage Resistance (9 to 13)
	{'name': 'Unset Ring', 'implicit': ['Has 1 Socket']},  # Local Has (1) Sockets
	{'name': 'Iolite Ring', 'implicit': ['% increased Chaos Damage']},  # (17-23)% increased Chaos Damage
	{'name': 'Opal Ring', 'implicit': ['% increased Elemental Damage']},  # Elemental Damage +(15 to 25)
	{'name': 'Steel Ring', 'implicit': ['Adds', 'Physical Damage to Attacks']},  # Minimum Added Physical Damage (3 to 4), Maximum Added Physical Damage (10 to 14)
	{'name': 'Vermillion Ring', 'implicit': ['% increased maximum Life']},  # (5 to 7)% increased maximum Life
	{'name': 'Cerulean Ring', 'implicit': ['% increased maximum Mana']},  # (8 to 10)% increased maximum Mana

	{'name': 'Two-Point Arrow Quiver', 'implicit': ['% increased Global Accuracy Rating']},  # (20-30)% increased Global Accuracy Rating
	{'name': 'Serrated Arrow Quiver', 'implicit': ['1 to 4 Added Physical Damage with Bow Attacks']},  # Adds 1 to 4 Physical Damage to Bow Attacks
	{'name': 'Sharktooth Arrow Quiver', 'implicit': ['Life gained for each Enemy hit by your Attacks']},  # +(3-4) Life gained for each Enemy hit by your Attacks
	{'name': 'Blunt Arrow Quiver', 'implicit': ['% increased Stun Duration on Enemies']},  # (25-35)% increased Stun Duration on Enemies
	{'name': 'Fire Arrow Quiver', 'implicit': ['4 to 8 Added Fire Damage with Bow Attacks']},  # Adds 4 to 8 Fire Damage to Bow Attacks
	{'name': 'Broadhead Arrow Quiver', 'implicit': ['6 to 12 Added Physical Damage with Bow Attacks']},  # Adds 6 to 12 Physical Damage to Bow Attacks
	{'name': 'Penetrating Arrow Quiver', 'implicit': ['Arrows Pierce an additional Target']},  # Arrows Pierce an additional Target
	{'name': 'Ornate Quiver', 'implicit': ['Has 1 Socket']},  # Has 1 Socket
	{'name': 'Spike-Point Arrow Quiver', 'implicit': ['% increased Global Critical Strike Chance']},  # (20-30)% increased Global Critical Strike Chance
	{'name': 'Artillery Quiver', 'implicit': ['% increased Totem Placement speed']},  # (20-30)% increased Totem Placement Speed

	{'name': 'Cobalt Jewel'},
	{'name': 'Crimson Jewel'},
	{'name': 'Viridian Jewel'},
]
