subnames = {
	"tricorne": ['sinner tricorne'],
	"silk gloves": ['fingerless silk gloves'],
}

ngrams = {
	"abyssal axe": {"sal a"},
	"agate amulet": {" an", " i", "agat", "amu", "d i", "e am", "elli", "gat", "gence", "gt", "gth ", "lli", "nd ", "o s", "te a", "tel", "ule"},
	"amber amulet": {"amu", "gt", "o s", "r am", "ule"},
	"ambusher": {"sher", "ushe"},
	"amethyst ring": {"ao", "s re", "t ri", "t rin", "thy", "yst"},
	"antique greaves": {"e gr"},
	"antique rapier": {"ue r", "ue ra"},
	"apothecary's gloves": {"ary", "d d", "d da", "ed d", "er ", "hec", "pot", "time", "y'"},
	"archon kite shield": {"hon", "on k"},
	"artillery quiver": {"rti", "til", "uiv"},
	"assassin bow": {"sin b"},
	"assassin's garb": {"n's g"},
	"assassin's mitts": {"'s m"},
	"astral plate": {"astr"},
	"auric mace": {"uri"},
	"aventail helmet": {"tai", "ven"},
	"awl": {"wl"},
	"baroque round shield": {"oq", "ue r"},
	"basket rapier": {"sket"},
	"bastard sword": {"asta"},
	"blue pearl amulet": {" man", " reg", "a r", "amu", "blu", "ear", "egen", "l am", "sed ma", "ule"},
	"blunt arrow quiver": {"blu", "lun", "lunt", "nt a", "uiv", "w q"},
	"bone armour": {"ne ar"},
	"bone circlet": {"cle", "irc", "ne c", "one c"},
	"bone helmet": {" de", " dea", "d d", "d da", "dea", "ed d", "nio", "ns ", "s d"},
	"boot blade": {"oot b", "t bl"},
	"boot knife": {"t k"},
	"branded kite shield": {"bra", "bran", "rand"},
	"brass maul": {"bra", "bras", "ss m"},
	"brass spirit shield": {"bra", "bras", "s sp"},
	"broadhead arrow quiver": {"arr", "cal damage ", "d p", "d ph", "dh", "uiv", "w ", "w a"},
	"bronze gauntlets": {"ze g"},
	"bronze sceptre": {"ze s"},
	"bronzescale boots": {"escale b", "zes"},
	"bronzescale gauntlets": {"escale g", "zes"},
	"buckskin tunic": {"ckskin tu", "kskin tu"},
	"callous mask": {"lou"},
	"cardinal round shield": {"card", "ina"},
	"carnal armour": {" man", "l ar", "nal a", "o maximum m", "um m"},
	"carnal boots": {"al bo", "al boo", "nal b"},
	"carnal mitts": {"l mi", "l mit"},
	"carved wand": {"arve", "d w", "ed w", "ved w"},
	"cedar tower shield": {"eda"},
	"cerulean ring": {" man", "an r", "d max", "n ri", "rul", "sed ma", "ule", "um m"},
	"chain belt": {"bel", "gy ", "m e", "n be"},
	"chain gloves": {"ain g"},
	"champion kite shield": {"on k", "pio"},
	"chiming spirit shield": {"him", "ng sp"},
	"citrine amulet": {" an", " de", "amu", "d d", "d de", "e am", "gt", "gth ", "itr", "ity", "nd ", "nd d", "o s", "ty", "ule", "xt"},
	"clasped boots": {"clas", "sped b"},
	"clasped mitts": {"clas", "d mi", "sped m"},
	"cleaver": {"cle", "leav"},
	"close helmet": {"clo", "ose"},
	"cloth belt": {" an", "and b", "bel", "clo", "nd ", "un a"},
	"cobalt jewel": {"cob", "wel"},
	"colossal tower shield": {"al t", "l to"},
	"compound spiked shield": {"nd sp"},
	"conjurer boots": {"rer b", "urer b"},
	"conjurer gloves": {"r g", "rer g", "urer g"},
	"conquest chainmail": {"nq"},
	"convoking wand": {"an ", "an r", "l mi", "nio", "nv"},
	"copper plate": {"er p", "per p"},
	"coral amulet": {" se", "al am", "amu", "egen", "er ", "l am", "oral", "ule"},
	"coral ring": {"al ri", "oral", "ral r"},
	"corrugated buckler": {"gat", "rru", "ted bu"},
	"corsair sword": {"air"},
	"crimson jewel": {"jew", "n j", "on j"},
	"crude bow": {"rud", "ud"},
	"crusader chainmail": {"der c", "er c", "r c", "r ch"},
	"crusader gloves": {"der g", "r g"},
	"crusader plate": {"der p", "er p"},
	"crystal belt": {"bel", "crys", "gy ", "l be", "m e", "yst"},
	"crystal sceptre": {"crys", "tal s", "yst"},
	"crystal wand": {"al w", "l w", "stal", "tal w", "yst"},
	"cutthroat's garb": {"hro", "oat'", "tth"},
	"death bow": {"dea", "deat"},
	"decimation bow": {"cim", "on b"},
	"decorative axe": {"deco"},
	"deerskin boots": {"dee", "rskin b"},
	"deerskin gloves": {"dee", "rskin g"},
	"deicide mask": {"cid", "dei"},
	"demon dagger": {"dem", "n da"},
	"demon's horn": {"dem", "mon'", "on'"},
	"desert brigandine": {"des", "ert", "rt b"},
	"despot axe": {"des", "pot", "spo"},
	"destiny leather": {"des", "dest", "y l"},
	"destroyer regalia": {"des", "dest", "tro"},
	"diamond ring": {"d ri", "iam"},
	"dragonscale boots": {"gonscale b", "nscale b"},
	"dragonscale gauntlets": {"gonscale g", "nscale g"},
	"dread maul": {"dre", "read"},
	"dream mace": {"dre", "eam"},
	"driftwood wand": {"d w", "od w"},
	"dusk blade": {"dus"},
	"ebony tower shield": {"bony", "eb", "ony"},
	"eelskin gloves": {"lskin g"},
	"elder sword": {"elde"},
	"elegant ringmail": {"nt r", "nt ri", "t ri", "t rin"},
	"elegant round shield": {"nt r", "nt ro"},
	"elegant sword": {"ant s"},
	"embroidered gloves": {"ider", "oid", "red g", "roi"},
	"engraved wand": {"aved w", "d w", "ed w", "ved w"},
	"estoc": {"toc"},
	"etched greatsword": {"hed g"},
	"eternal burgonet": {"ernal", "eter", "nal b", "nal bu"},
	"eternal sword": {"ernal", "eter", "nal sw", "ternal s"},
	"ezomyte axe": {"te a", "yte a"},
	"ezomyte blade": {"yte b", "yte bl"},
	"ezomyte burgonet": {"e bur", "yte b"},
	"ezomyte dagger": {"e da", "te d"},
	"ezomyte staff": {"te st"},
	"festival mask": {"iva", "l mas"},
	"fiend dagger": {"d d", "d da", "iend", "nd d"},
	"fingerless silk gloves": {"erl", "inge", "k g", "lk g", "nger"},
	"fingerless silk gloves§silk gloves": {"erl", "inge", "nger"},
	"fire arrow quiver": {" fi", "arr", "d fi", "e da", "e dam", "re a", "re d", "uiv", "w ", "w a"},
	"flaying knife": {"yi"},
	"fossilised spirit shield": {"ed spir", "fos", "ili", "ise"},
	"fright claw": {"ht c"},
	"fugitive boots": {"ao", "fug", "s re"},
	"full dragonscale": {"l dr"},
	"full wyrmscale": {"l w", "l wy"},
	"gavel": {"gav"},
	"gilded sallet": {"d sa", "ded sa"},
	"gladiator plate": {"or p"},
	"gladius": {"diu"},
	"glorious plate": {"s pl"},
	"gnarled branch": {"bra", "bran", "nch"},
	"goat's horn": {"goat'", "oat'", "t's h"},
	"goathide boots": {"thide bo"},
	"goathide gloves": {"thide g"},
	"gold amulet": {" i", "amu", "d am", "ity", "ld a", "s f", "ty", "ty ", "ule"},
	"gold ring": {" i", "d ri", "ity", "ld r", "ld ri", "old r", "s f", "ty", "ty "},
	"golden buckler": {"en b", "n bu"},
	"golden mask": {"den m", "en m"},
	"golden plate": {"en p"},
	"goliath gauntlets": {"h ga"},
	"great crown": {"at c", "t cr"},
	"great helmet": {"at h", "t h"},
	"great mallet": {"at m"},
	"grinning fetish": {"eti", "gri", "grin", "nn", "nni", "tis"},
	"gripped gloves": {"d p", "gri", "oj", "til", "tile"},
	"gut ripper": {"t ri", "ut r"},
	"harbinger bow": {"bi", "ger b", "inge", "nger"},
	"harmonic spirit shield": {"c s", "rmon"},
	"headsman axe": {"an a", "ds", "dsm"},
	"heavy belt": {"bel", "gt", "o s", "vy"},
	"hellion's paw": {"elli", "ion'", "lio", "lli", "llio", "on'"},
	"highborn staff": {"rn s"},
	"highland blade": {"hl", "nd bl"},
	"holy chainmail": {"oly", "y c"},
	"hubris circlet": {"cle", "hub", "irc", "s c"},
	"hydrascale gauntlets": {"ascale g"},
	"imbued wand": {"bue", "d w", "ed w"},
	"imperial bow": {"al bo", "al bow", "ial bo"},
	"imperial claw": {"ial c", "l cla"},
	"imperial maul": {"d str", "gt"},
	"imperial skean": {"ial s", "ial sk", "l sk", "rial s"},
	"imperial staff": {"al sta", "ial s", "ial st", "rial s", "rial st"},
	"infernal axe": {"ernal", "fer", "nal a", "nal ax"},
	"infernal sword": {"ernal", "fer", "fernal s", "nal sw"},
	"iolite ring": {"ao", "e ri", "iol", "s d", "te r"},
	"iron circlet": {"cle", "irc", "n ci"},
	"iron gauntlets": {"n gau", "on ga"},
	"iron hat": {"ron h"},
	"iron mask": {"ron m"},
	"iron ring": {"cal damage ", "dds", "ds", "n ri", "on ri", "ron r"},
	"iron staff": {"ron st"},
	"ironscale boots": {"nscale b", "rons", "ronscale b"},
	"ironscale gauntlets": {"nscale g", "rons", "ronscale g"},
	"ivory spirit shield": {"ry s", "y sp"},
	"jade amulet": {" de", "amu", "de a", "e am", "ity", "o de", "o dex", "ty", "ule", "xt"},
	"jade hatchet": {"de h"},
	"jagged foil": {"ged f", "jag"},
	"jagged maul": {"gged m", "jag"},
	"jasper chopper": {"er c", "per c", "r c", "r ch"},
	"jewelled foil": {"lled", "wel"},
	"jingling spirit shield": {"ji", "ng sp"},
	"judgement staff": {"ud", "udg"},
	"karui chopper": {"i ch"},
	"karui maul": {"i m"},
	"karui sceptre": {"i s"},
	"lacquered buckler": {"cq", "uered b"},
	"lacquered garb": {"cq", "red g", "red ga"},
	"lacquered helmet": {"cq", "d helme"},
	"laminated kite shield": {"ina", "inat"},
	"lapis amulet": {" i", "amu", "elli", "gence", "lli", "o i", "s a", "tel", "ule"},
	"lathi": {"lath"},
	"latticed ringmail": {"d ri", "ed ri", "ice"},
	"leather belt": {"bel", "r be"},
	"leather cap": {"cap", "er c", "her c", "r c"},
	"leather hood": {"her h"},
	"legion boots": {"gion b", "on b"},
	"legion gloves": {"on gl"},
	"legion sword": {"gion s", "ion s"},
	"lion pelt": {"lio", "n pe"},
	"lion sword": {" an", " de", "d d", "d de", "gt", "gth ", "ion s", "ity", "lio", "lion s", "nd ", "nd d", "o s", "ty", "xt"},
	"long bow": {"g b"},
	"loricated ringmail": {"cate", "d ri", "ed ri", "ted r"},
	"lunaris circlet": {"aris c", "cle", "irc", "lun", "s c", "una"},
	"maelström staff": {"ae", "ö"},
	"marble amulet": {" se", "amu", "e am", "egen", "er ", "rbl", "ule"},
	"meatgrinder": {" de", " dea", " dou", "dea", "e da", "e dam", "gri", "grin", "o de", "tg"},
	"mesh boots": {"esh b", "mes"},
	"mesh gloves": {"mes", "sh g"},
	"midnight blade": {"dn", "ht bl", "t bl"},
	"military staff": {"ary", "ili", "lita", "mil", "ry s"},
	"mind cage": {"mind", "nd c"},
	"mirrored spiked shield": {"irr", "ore", "ror"},
	"moonstone ring": {"e ri", "gy ", "m e", "ne ri", "nst"},
	"mosaic kite shield": {"mos"},
	"murder mitts": {"der m"},
	"nailed fist": {"d fi", "nai"},
	"necromancer circlet": {"cle", "er c", "irc", "oma", "r c", "r ci", "rom"},
	"necromancer silks": {"lks", "oma", "rom"},
	"nightmare bascinet": {"re b"},
	"nubuck boots": {"ck b", "ck bo", "nub"},
	"nubuck gloves": {"ck g", "k g", "nub"},
	"occultist's vestment": {"st'", "tis"},
	"onyx amulet": {"amu", "ony", "ule", "yx"},
	"opal ring": {"al ri", "opa", "pal", "pal r"},
	"opal sceptre": {"opa", "pal", "pal s"},
	"opal wand": {"al w", "l w", "opa", "pal", "pal w"},
	"ornate mace": {"te m"},
	"ornate ringmail": {"ate r", "e ri", "te r"},
	"ornate sword": {"te sw"},
	"painted buckler": {"nted b", "ted bu"},
	"paua amulet": {" man", " reg", "a a", "a r", "amu", "aua", "egen", "sed ma", "ule"},
	"paua ring": {" man", "a r", "aua", "o maximum m", "ua r", "um m"},
	"penetrating arrow quiver": {" an", " ta", "al t", "an ", "an a", "arg", "arr", "e an", "uiv", "ws"},
	"pine buckler": {"ne bu", "pine"},
	"pinnacle tower shield": {"acl", "cle", "nn"},
	"plague mask": {"lag"},
	"plank kite shield": {"k k"},
	"plate vest": {"te v"},
	"plated greaves": {"d greav", "ted gr"},
	"platinum kris": {"inu", "m k"},
	"platinum sceptre": {"m sc", "num"},
	"poleaxe": {"ole", "pol"},
	"polished spiked shield": {"pol", "poli"},
	"praetor crown": {"ae", "or c", "pra", "r c"},
	"primordial staff": {"al sta", "ial s", "ial st", "imo"},
	"prophecy wand": {"ecy", "hec", "phe"},
	"prophet crown": {"et c", "oph", "t cr"},
	"quartz wand": {"z w"},
	"ranger bow": {"anger", "ger b", "nger"},
	"raven mask": {"en m", "raven", "ven"},
	"rawhide tower shield": {"de t"},
	"reaver sword": {"ver s"},
	"recurve bow": {"recu"},
	"regicide mask": {"cid", "gic"},
	"reinforced greaves": {"ced g", "d greav"},
	"reinforced tower shield": {"ced t"},
	"ritual sceptre": {"itu"},
	"riveted boots": {"eted b"},
	"rock breaker": {"bre", "ck b", "eak", "ker"},
	"rotted round shield": {"rot", "ted r"},
	"royal axe": {"yal a"},
	"royal bow": {"al bo", "al bow", "yal bo"},
	"royal sceptre": {"yal s", "yal sc"},
	"royal skean": {"l sk", "yal s", "yal sk"},
	"royal staff": {"al sta", "yal s", "yal st"},
	"ruby ring": {"o f", "re ", "re r", "rub"},
	"rusted sword": {"ted sw"},
	"rustic sash": {"ash", "c s"},
	"sabre": {"bre", "sab"},
	"sadist garb": {"dis"},
	"sage wand": {"ge wa", "sag"},
	"sage's robe": {"sag", "sage'"},
	"saint's hauberk": {"int'", "sain", "t's h"},
	"saintly chainmail": {"sain", "tly", "y c"},
	"samite gloves": {"te g"},
	"samnite helmet": {"mn"},
	"sapphire ring": {" co", "e ri", "ld ", "ld r", "old r", "pph", "re r"},
	"satin gloves": {"tin g"},
	"scholar boots": {"lar b", "sch"},
	"scholar's robe": {"ar'", "sch"},
	"seaglass amulet": {"amu", "arg", "er ", "gy ", "ld ", "ld r", "s a", "t o", "ule"},
	"secutor helm": {"uto"},
	"sentinel jacket": {"enti", "l j"},
	"serpentine staff": {"penti", "tine"},
	"serpentscale gauntlets": {"tscale g"},
	"serrated arrow quiver": {"arr", "cal damage ", "d p", "d ph", "ted a", "uiv", "w ", "w a"},
	"shadow axe": {"ado", "dow", "had", "w a", "w ax"},
	"shadow sceptre": {"ado", "dow", "had", "w sc"},
	"shagreen boots": {"en b", "en bo"},
	"shagreen gloves": {"een g"},
	"sharkskin boots": {"kskin b"},
	"sharkskin tunic": {"kskin tu", "rkskin t"},
	"sharktooth arrow quiver": {"arr", "uiv", "ur ", "yo"},
	"short bow": {"rt b", "shor"},
	"siege axe": {"ege a"},
	"silk gloves": {"k g", "lk g"},
	"silk slippers": {"lk s"},
	"silken hood": {"en h"},
	"simple robe": {"sim"},
	"sinner tricorne": {"nn", "nne"},
	"sinner tricorne§tricorne": {"nn", "nne"},
	"skinning knife": {"kinn", "nn", "nni"},
	"slaughter knife": {"hte"},
	"sledgehammer": {"eha"},
	"slink gloves": {"k g", "nk g"},
	"solaris circlet": {"aris c", "cle", "irc", "lari", "s c"},
	"soldier boots": {"ier b"},
	"soldier gloves": {"ier g", "r g"},
	"soldier helmet": {"ier h"},
	"sorcerer boots": {"erer", "erer b", "rer b", "sor"},
	"sorcerer gloves": {"erer", "erer g", "r g", "rer g", "sor"},
	"spidersilk robe": {"ider", "pid", "rsi"},
	"spike-point arrow quiver": {"-p", "arr", "e-", "nt a", "uiv"},
	"spiked club": {"ked c"},
	"spiked gloves": {"e da", "e dam", "ee "},
	"spine bow": {"pine", "spine"},
	"spiraled wand": {"d w", "ed w", "led w"},
	"stealth boots": {"lth b"},
	"steel circlet": {"cle", "el c", "irc", "l ci"},
	"steel gauntlets": {"el ga", "l ga"},
	"steel kite shield": {"el k"},
	"steel ring": {"cal damage ", "dds", "ds", "el r"},
	"steelhead": {"lh"},
	"steelscale gauntlets": {"lscale g"},
	"stiletto": {"til", "tile", "tto"},
	"strapped boots": {"strap", "trapped b"},
	"strapped leather": {"d le", "ed l", "strap"},
	"strapped mitts": {"d mi", "pped m", "strap", "trapped m"},
	"studded belt": {"bel", "d be", "ed be", "tud", "ud"},
	"studded round shield": {"ded r", "tud", "ud"},
	"supreme spiked shield": {"up"},
	"tarnished spirit shield": {"arni", "ed spir", "tarn"},
	"teak round shield": {"ak r", "eak"},
	"terror claw": {"or c", "or cl", "r c", "r cl", "ror", "terr"},
	"terror maul": {" dou", "le st", "or m", "ror", "terr"},
	"thresher claw": {"er c", "eshe", "her c", "r c", "r cl", "sher"},
	"throat stabber": {"hro", "tab"},
	"tiger sword": {"ger s"},
	"timeworn claw": {"mew", "time"},
	"titan gauntlets": {"an g", "an ga", "n gau", "tit"},
	"titan greaves": {"an g", "an gr", "tit"},
	"titanium spirit shield": {"niu", "tit"},
	"tomahawk": {"oma", "wk"},
	"topaz ring": {"az", "opa", "tn"},
	"tornado wand": {"ado", "nad"},
	"tribal circlet": {"al ci", "cle", "irc", "l ci"},
	"tricorne": {"tric"},
	"triumphant lamellar": {"t l"},
	"turquoise amulet": {" an", " de", " i", "amu", "d i", "e am", "elli", "ise", "ity", "lli", "nd ", "o de", "o dex", "tel", "ty", "ty ", "ule", "uo", "xt"},
	"twilight blade": {"ht bl", "ili", "t bl", "twil", "wil"},
	"two-point arrow quiver": {"-p", "arr", "nt a", "o-p", "uiv"},
	"two-stone ring": {" an", " co", " fi", "-s", "e an", "e ri", "ld ", "ld a", "ld r", "nd ", "nd c", "nd l", "ne ri", "o f", "old r", "re a", "tn"},
	"two-toned boots": {" an", " co", " fi", "-t", "e an", "ld ", "ld a", "ld r", "nd ", "nd c", "nd l", "o f", "old r", "re a", "tn"},
	"tyrant's sekhem": {"ty", "yra"},
	"unset ring": {"has", "t ri", "t rin"},
	"ursine pelt": {"rsi", "urs"},
	"vaal axe": {"m o"},
	"vaal blade": {"aal b", "l bl"},
	"vaal buckler": {"aal b", "aal bu"},
	"vaal claw": {"aal c", "l cla"},
	"vaal gauntlets": {"al ga", "l ga"},
	"vaal hatchet": {"l ha"},
	"vaal mask": {"aal m", "l mas"},
	"vaal regalia": {"l reg"},
	"vaal sceptre": {"aal sc"},
	"vanguard belt": {" an", "bel", "d be", "nd ", "ngu", "ur "},
	"varnished coat": {"arni", "varn"},
	"velvet gloves": {"et g", "lv"},
	"velvet slippers": {"et s", "lv"},
	"vermillion ring": {"d max", "erm", "lio", "lli", "llio", "mil", "n ri", "on ri", "sed ma"},
	"vile staff": {"le st", "vil"},
	"vine circlet": {"cle", "irc", "ne c", "vine"},
	"viridian jewel": {"idi", "jew", "n j"},
	"visored sallet": {"d sa", "iso", "ore", "sor"},
	"void axe": {"id a", "oid", "voi"},
	"void sceptre": {"id s", "oid", "voi"},
	"war buckler": {"war b"},
	"war hammer": {"ar h"},
	"war sword": {"war s"},
	"whalebone rapier": {"eb", "hal"},
	"widowsilk robe": {"dow", "ido", "ws"},
	"wild leather": {"d le", "wil", "wild"},
	"woodsplitter": {"ds", "ods"},
	"wool gloves": {"ol g", "ool"},
	"wool shoes": {"oe", "ool"},
	"wrapped mitts": {"d mi", "pped m", "wrapped m"},
	"wyrmscale doublet": {"mscale d"},
	"wyrmscale gauntlets": {"mscale g"},
	"zealot gloves": {"ot g"},
	"zealot helmet": {"ot h", "t h"},
	"zodiac leather": {"c l"},
}