subnames = {
	"tricorne": ['sinner tricorne'],
	"silk gloves": ['fingerless silk gloves'],
}

ngrams = {
	"abyssal axe": {"sal a"},
	"agate amulet": {"agat", "amu", "e am", "gat", "te a", "ule"},
	"amber amulet": {"ambe", "amu", "ule"},
	"ambusher": {"sher", "ushe"},
	"amethyst ring": {"t ri", "t rin", "thy", "yst"},
	"antique greaves": {"e gr"},
	"antique rapier": {"ue r", "ue ra"},
	"apothecary's gloves": {"ary", "hec", "pot", "y'"},
	"arcanist gloves": {"ani", "arc", "rca", "st g", "st gl", "t gl"},
	"arcanist slippers": {"ani", "arc", "ist s", "rca", "t sl"},
	"archon kite shield": {"arc", "hon", "on k"},
	"assassin bow": {"sin b"},
	"assassin's garb": {"n's g"},
	"assassin's mitts": {"'s m"},
	"astral plate": {"astr"},
	"auric mace": {"aur"},
	"aventail helmet": {"tai", "ven"},
	"awl": {"wl"},
	"baroque round shield": {"oq", "ue r"},
	"basket rapier": {"aske"},
	"bastard sword": {"asta"},
	"blazing arrow quiver": {"az", "g ar", "zi"},
	"blue pearl amulet": {"amu", "blu", "ear", "l am", "ule"},
	"blunt arrow quiver": {"blu", "blun", "lun", "nt a"},
	"bone armour": {"ne ar"},
	"bone circlet": {"cir", "cle", "e ci", "one c"},
	"bone helmet": {"bone h"},
	"boot blade": {"oot b", "t bl"},
	"boot knife": {"t k"},
	"branded kite shield": {"bra", "bran", "rand"},
	"brass maul": {"bra", "bras", "ss m"},
	"brass spirit shield": {"bra", "bras", "s sp"},
	"bronze gauntlets": {"ze g"},
	"bronze sceptre": {"ze s"},
	"bronzescale boots": {"escale b", "zes"},
	"bronzescale gauntlets": {"escale g", "zes"},
	"buckskin tunic": {"ckskin tu", "kskin tu"},
	"callous mask": {"lou"},
	"cardinal round shield": {"card", "ina"},
	"carnal armour": {"arn", "arna", "l arm", "nal a", "rnal"},
	"carnal boots": {"al bo", "al boo", "arn", "arna", "nal b", "rnal"},
	"carnal mitts": {"al mi", "arn", "arna", "rnal"},
	"carnal sceptre": {"arn", "arna", "nal s", "nal sc", "rnal"},
	"carved wand": {"arv", "arve", "d w", "ed w", "ved w"},
	"carving knife": {"arv", "rvi", "vi", "vin"},
	"cedar tower shield": {"eda"},
	"cerulean ring": {"eru", "n ri", "ule"},
	"chain belt": {"bel", "n be"},
	"chain gloves": {"ain g"},
	"champion kite shield": {"amp", "on k"},
	"chiming spirit shield": {"chi", "ng sp"},
	"citrine amulet": {"amu", "e am", "itr", "ule"},
	"clasped boots": {"clas", "sped b"},
	"clasped mitts": {"clas", "d mi", "sped m"},
	"cleaver": {"cle", "clea"},
	"close helmet": {"clo", "ose"},
	"cloth belt": {"bel", "clo", "clot"},
	"cobalt jewel": {"cob", "ewe"},
	"colossal tower shield": {"l to"},
	"compound spiked shield": {"nd sp"},
	"conjurer boots": {"rer b", "urer b"},
	"conjurer gloves": {"r g", "rer g", "urer g"},
	"conquest chainmail": {"nq"},
	"convoking wand": {"nv"},
	"copper plate": {"er p", "per p"},
	"coral amulet": {"al am", "amu", "l am", "oral", "ule"},
	"coral ring": {"al ri", "oral", "ral r"},
	"corrugated buckler": {"gat", "rru", "ted bu"},
	"corsair sword": {"air"},
	"crimson jewel": {"ewe", "n j", "on j"},
	"crude bow": {"de bo", "rud", "ud"},
	"crusader chainmail": {"der c", "er c", "r c", "r ch"},
	"crusader gloves": {"der g", "r g"},
	"crusader plate": {"der p", "er p"},
	"crystal belt": {"bel", "crys", "l be", "yst"},
	"crystal sceptre": {"crys", "tal s", "yst"},
	"crystal wand": {"al w", "crys", "l w", "tal w", "yst"},
	"cutthroat's garb": {"hro", "oat'", "tth"},
	"death bow": {"deat"},
	"decimation bow": {"cim", "on b"},
	"decorative axe": {"ativ"},
	"deerskin boots": {"dee", "rskin b"},
	"deerskin gloves": {"dee", "rskin g"},
	"deicide mask": {"cid", "dei"},
	"demon dagger": {"dem", "n da"},
	"demon's horn": {"dem", "mon'", "on'"},
	"desert brigandine": {"des", "ert", "rt b"},
	"despot axe": {"des", "esp", "pot"},
	"destiny leather": {"des", "dest", "y l"},
	"destroyer regalia": {"des", "dest", "tro"},
	"diamond ring": {"amo", "d ri"},
	"dragonscale boots": {"gonscale b", "nscale b"},
	"dragonscale gauntlets": {"gonscale g", "nscale g"},
	"dread maul": {"ad m", "dre"},
	"dream mace": {"dre", "eam"},
	"driftwood wand": {"d w", "od w"},
	"dusk blade": {"dus"},
	"ebony tower shield": {"bony", "eb", "ony"},
	"eelskin gloves": {"lskin g"},
	"elder sword": {"elde"},
	"elegant ringmail": {"nt r", "nt ri", "t ri", "t rin"},
	"elegant round shield": {"nt r", "nt ro"},
	"elegant sword": {"ant s"},
	"embroidered gloves": {"emb", "ider", "oid", "red g"},
	"engraved wand": {"aved w", "d w", "ed w", "ved w"},
	"estoc": {"toc"},
	"etched greatsword": {"hed g"},
	"eternal burgonet": {"ernal", "eter", "nal b", "nal bu", "rnal"},
	"eternal sword": {"ernal", "eter", "nal s", "nal sw", "rnal", "ternal s"},
	"exquisite leather": {"te l"},
	"ezomyte axe": {"te a", "te ax"},
	"ezomyte blade": {"yte b", "yte bl"},
	"ezomyte burgonet": {"e bur", "yte b"},
	"ezomyte dagger": {"te d"},
	"ezomyte staff": {"te st"},
	"feathered arrow quiver": {"ed arrow q", "fea"},
	"festival mask": {"fes", "l mas"},
	"fiend dagger": {"fien"},
	"fingerless silk gloves": {"erl", "inge", "k g", "lk g", "nger"},
	"fingerless silk gloves§silk gloves": {"erl", "inge", "nger"},
	"flaying knife": {"yi"},
	"fossilised spirit shield": {"ed spir", "fos", "ili", "ise"},
	"fright claw": {"ht c"},
	"fugitive boots": {"fug"},
	"full dragonscale": {"l dr"},
	"full wyrmscale": {"l w", "l wy"},
	"gavel": {"gav"},
	"gilded sallet": {"d sa", "ded sa"},
	"gladiator plate": {"or p"},
	"gladius": {"diu"},
	"glorious plate": {"s pl"},
	"gnarled branch": {"bra", "bran", "nch"},
	"goat's horn": {"goat'", "oat'", "t's h"},
	"goathide boots": {"de bo", "de boo", "thide bo"},
	"goathide gloves": {"thide g"},
	"gold amulet": {"amu", "d am", "ule"},
	"gold ring": {"d ri", "ld ri"},
	"golden mask": {"den m", "en m", "n mas"},
	"golden plate": {"en p"},
	"goliath gauntlets": {"h ga"},
	"great crown": {"at c", "t cr"},
	"great helmet": {"at h", "t h"},
	"great mallet": {"at m"},
	"grinning fetish": {"eti", "gri", "grin", "nn", "nni", "tis"},
	"gripped gloves": {"gri", "grip"},
	"gut ripper": {"t ri", "ut r"},
	"harbinger bow": {"bi", "ger b", "inge", "nger"},
	"harlequin mask": {"leq", "n mas"},
	"harmonic spirit shield": {"c s", "c sp"},
	"headsman axe": {"ads"},
	"heavy arrow quiver": {"vy", "vy a"},
	"heavy belt": {"bel", "vy", "vy b"},
	"hellion's paw": {"hell", "lio", "llio", "on'"},
	"highborn staff": {"rn s"},
	"highland blade": {"hl"},
	"holy chainmail": {"oly", "y c"},
	"hubris circlet": {"cir", "cle", "hub", "s c"},
	"hydrascale gauntlets": {"ascale g"},
	"imbued wand": {"bue", "d w", "ed w"},
	"imperial bow": {"al bo", "al bow", "ial bo"},
	"imperial claw": {"ial c", "l cla"},
	"imperial maul": {"rial m"},
	"imperial skean": {"ial s", "ial sk", "l sk", "rial s"},
	"imperial staff": {"al sta", "ial s", "ial st", "rial s", "rial st"},
	"infernal axe": {"ernal", "fer", "nal a", "nal ax", "rnal"},
	"infernal sword": {"ernal", "fer", "fernal s", "nal s", "nal sw", "rnal"},
	"iolite ring": {"e ri", "iol", "te r"},
	"iron circlet": {"cir", "cle", "n ci"},
	"iron gauntlets": {"n gau", "on ga"},
	"iron hat": {"n hat"},
	"iron mask": {"n mas", "ron m"},
	"iron ring": {"n ri", "on ri", "ron r"},
	"iron staff": {"ron st"},
	"ironscale boots": {"nscale b", "rons", "ronscale b"},
	"ironscale gauntlets": {"nscale g", "rons", "ronscale g"},
	"ivory spirit shield": {"ry s", "y sp"},
	"jade amulet": {"amu", "de a", "e am", "ule"},
	"jade hatchet": {"de h"},
	"jagged foil": {"ged f", "jag"},
	"jagged maul": {"gged m", "jag"},
	"jasper chopper": {"er c", "per c", "r c", "r ch"},
	"jewelled foil": {"elle", "ewe"},
	"jingling spirit shield": {"ji", "ng sp"},
	"judgement staff": {"jud", "ud"},
	"karui chopper": {"i ch"},
	"karui maul": {"i m"},
	"karui sceptre": {"i s"},
	"lacquered buckler": {"cq", "uered b"},
	"lacquered garb": {"cq", "red g", "red ga"},
	"lacquered helmet": {"cq", "d helme"},
	"laminated kite shield": {"amin", "ina"},
	"lapis amulet": {"amu", "lap", "s a", "ule"},
	"lathi": {"lath"},
	"latticed ringmail": {"d ri", "ed ri", "ice"},
	"leather belt": {"bel", "r be"},
	"leather cap": {"cap", "er c", "her c", "r c"},
	"leather hood": {"her h"},
	"legion boots": {"gion b", "on b"},
	"legion gloves": {"ion g"},
	"legion sword": {"gion s", "ion s"},
	"lion pelt": {"lio", "n pe"},
	"lion sword": {"ion s", "lio", "lion s"},
	"long bow": {"g b"},
	"loricated ringmail": {"cate", "d ri", "ed ri", "ted r"},
	"lunaris circlet": {"aris c", "cir", "cle", "lun", "s c", "una"},
	"maelström staff": {"ae", "ö"},
	"marble amulet": {"amu", "e am", "rbl", "ule"},
	"meatgrinder": {"gri", "grin", "tg"},
	"mesh boots": {"esh b", "mes"},
	"mesh gloves": {"mes", "sh g"},
	"midnight blade": {"dn", "ht bl", "t bl"},
	"military staff": {"ary", "ili", "ilit", "mil", "ry s"},
	"mind cage": {"mind"},
	"mirrored spiked shield": {"irr", "ore", "ror"},
	"moonstone ring": {"e ri", "ne ri", "nst"},
	"mosaic kite shield": {"aic"},
	"murder mitts": {"der m"},
	"nailed fist": {"nai"},
	"necromancer circlet": {"cir", "cle", "ecr", "er c", "oma", "r c", "r ci"},
	"necromancer silks": {"ecr", "lks", "oma"},
	"nightmare bascinet": {"e ba"},
	"nubuck boots": {"ck b", "ck bo", "nub"},
	"nubuck gloves": {"ck g", "k g", "nub"},
	"occultist's vestment": {"cul", "tis"},
	"onyx amulet": {"amu", "ony", "ule", "yx"},
	"opal ring": {"al ri", "opa", "pal", "pal r"},
	"opal sceptre": {"opa", "pal", "pal s"},
	"opal wand": {"al w", "l w", "opa", "pal", "pal w"},
	"ornate mace": {"te m"},
	"ornate ringmail": {"ate r", "e ri", "te r"},
	"ornate sword": {"te sw"},
	"painted buckler": {"nted b", "ted bu"},
	"paua amulet": {"a a", "amu", "aua", "ule"},
	"paua ring": {"a ri", "aua"},
	"penetrating arrow quiver": {"g ar", "trati"},
	"pine buckler": {"ne bu", "pine"},
	"pinnacle tower shield": {"acl", "cle", "nn"},
	"plague mask": {"agu"},
	"plank kite shield": {"k k"},
	"plate vest": {"te v"},
	"plated greaves": {"d greav", "ted gr"},
	"platinum kris": {"inu", "m k"},
	"platinum sceptre": {"inu", "m sc"},
	"poleaxe": {"eax", "pol"},
	"polished spiked shield": {"lish", "pol"},
	"praetor crown": {"ae", "aet", "or c", "r c"},
	"primordial staff": {"al sta", "ial s", "ial st", "imo"},
	"prophecy wand": {"ecy", "hec", "oph"},
	"prophet crown": {"et c", "oph", "t cr"},
	"quartz wand": {"z w"},
	"ranger bow": {"anger", "ger b", "nger"},
	"raven mask": {"en m", "n mas", "raven", "ven"},
	"rawhide boots": {"de bo", "de boo", "whide b"},
	"rawhide tower shield": {"de t"},
	"reaver sword": {"ver s"},
	"recurve bow": {"recu"},
	"regicide mask": {"cid", "gic"},
	"reinforced greaves": {"ced g", "d greav"},
	"reinforced tower shield": {"ced t"},
	"ritual sceptre": {"itu"},
	"riveted boots": {"eted b"},
	"rock breaker": {"bre", "ck b", "eak", "ker"},
	"rotted round shield": {"ott", "ted r"},
	"royal axe": {"yal a"},
	"royal bow": {"al bo", "al bow", "yal bo"},
	"royal sceptre": {"yal s", "yal sc"},
	"royal skean": {"l sk", "yal s", "yal sk"},
	"royal staff": {"al sta", "yal s", "yal st"},
	"ruby ring": {"rub"},
	"rusted sword": {"ted sw"},
	"rustic sash": {"ash", "c s"},
	"sabre": {"bre", "sab"},
	"sadist garb": {"dis", "st g"},
	"sage wand": {"ge wa", "sag"},
	"sage's robe": {"e's r", "sag"},
	"saint's hauberk": {"int'", "sain", "t's h"},
	"saintly chainmail": {"sain", "tly", "y c"},
	"samite gloves": {"te g"},
	"samnite helmet": {"mn"},
	"sapphire ring": {"e ri", "hir"},
	"satin gloves": {"tin g"},
	"scholar boots": {"ar bo", "sch"},
	"scholar's robe": {"ar'", "sch"},
	"seaglass amulet": {"amu", "s a", "sea", "ule"},
	"secutor helm": {"uto"},
	"sentinel jacket": {"enti", "l j"},
	"serpentine staff": {"enti", "ine s"},
	"serpentscale gauntlets": {"tscale g"},
	"serrated arrow quiver": {"ed arrow q", "ted a"},
	"shadow axe": {"ado", "dow", "had", "w ax"},
	"shadow sceptre": {"ado", "dow", "had", "w sc"},
	"shagreen boots": {"een b"},
	"shagreen gloves": {"een g"},
	"sharkskin boots": {"kskin b"},
	"sharkskin tunic": {"kskin tu", "rkskin t"},
	"sharktooth arrow quiver": {"h ar"},
	"short bow": {"hort", "rt b"},
	"siege axe": {"ege a"},
	"silk gloves": {"k g", "lk g"},
	"silk slippers": {"k sl"},
	"silken hood": {"en h"},
	"simple robe": {"sim"},
	"sinner tricorne": {"nn", "nne"},
	"sinner tricorne§tricorne": {"nn", "nne"},
	"skinning knife": {"kinn", "nn", "nni"},
	"slaughter knife": {"aug"},
	"sledgehammer": {"edg"},
	"slink gloves": {"k g", "nk g"},
	"solaris circlet": {"aris c", "cir", "cle", "lari", "s c"},
	"soldier boots": {"ier b"},
	"soldier gloves": {"ier g", "r g"},
	"soldier helmet": {"ier h"},
	"sorcerer boots": {"erer", "erer b", "rer b", "sor"},
	"sorcerer gloves": {"erer", "erer g", "r g", "rer g", "sor"},
	"spidersilk robe": {"ider", "pid", "rsi"},
	"spike-point arrow quiver": {"-p", "e-", "nt a"},
	"spiked club": {"ked c"},
	"spiked gloves": {"ked g"},
	"spine bow": {"pine", "spine"},
	"spiraled wand": {"d w", "ed w", "led w"},
	"stealth boots": {"lth b"},
	"steel circlet": {"cir", "cle", "el c", "l ci"},
	"steel gauntlets": {"el ga", "l ga"},
	"steel kite shield": {"el k"},
	"steel ring": {"el r"},
	"steelhead": {"lh"},
	"steelscale gauntlets": {"lscale g"},
	"stiletto": {"ett"},
	"strapped boots": {"strap", "trapped b"},
	"strapped leather": {"d le", "ed l", "strap"},
	"strapped mitts": {"d mi", "pped m", "strap", "trapped m"},
	"studded belt": {"bel", "d be", "ed be", "tud", "ud"},
	"studded round shield": {"ded r", "tud", "ud"},
	"supreme spiked shield": {"up"},
	"tarnished spirit shield": {"arn", "arni", "ed spir", "tarn"},
	"teak round shield": {"ak r", "eak"},
	"terror claw": {"erro", "or c", "or cl", "r c", "r cl", "ror"},
	"terror maul": {"erro", "or m", "ror"},
	"thresher claw": {"er c", "eshe", "her c", "r c", "r cl", "sher"},
	"throat stabber": {"bbe", "hro"},
	"tiger sword": {"ger s"},
	"timeworn claw": {"mew"},
	"titan gauntlets": {"an g", "an ga", "n gau", "tit"},
	"titan greaves": {"an g", "an gr", "tit"},
	"titanium spirit shield": {"ani", "niu", "tit"},
	"tomahawk": {"oma", "wk"},
	"topaz ring": {"az", "opa", "paz"},
	"tornado wand": {"ado", "nad"},
	"tribal circlet": {"al ci", "cir", "cle", "l ci"},
	"tricorne": {"tric"},
	"triumphant lamellar": {"mph"},
	"turquoise amulet": {"amu", "e am", "ise", "rq", "ule"},
	"twilight blade": {"ht bl", "ili", "ilig", "t bl", "wil"},
	"two-point arrow quiver": {"-p", "nt a", "o-p"},
	"two-stone ring": {"-s", "e ri", "ne ri"},
	"two-toned boots": {"-t"},
	"tyrant's sekhem": {"tyr"},
	"unset ring": {"nse", "t ri", "t rin"},
	"ursine pelt": {"rsi", "urs"},
	"vaal axe": {"aal a"},
	"vaal blade": {"aal b", "l bl"},
	"vaal buckler": {"aal b", "aal bu"},
	"vaal claw": {"aal c", "l cla"},
	"vaal gauntlets": {"al ga", "l ga"},
	"vaal hatchet": {"al h"},
	"vaal mask": {"aal m", "l mas"},
	"vaal regalia": {"l reg"},
	"vaal sceptre": {"aal sc"},
	"vanguard belt": {"bel", "d be", "gua"},
	"varnished coat": {"arn", "arni", "varn"},
	"velvet gloves": {"et g", "lv", "t gl"},
	"velvet slippers": {"et s", "lv", "t sl"},
	"vermillion ring": {"erm", "lio", "llio", "mil", "n ri", "on ri"},
	"vile arrow quiver": {"ile ar", "vi", "vil"},
	"vile staff": {"ile s", "vi", "vil"},
	"vine circlet": {"cir", "cle", "e ci", "vi", "vin", "vine"},
	"viridian jewel": {"ewe", "ian", "n j", "vi"},
	"visored sallet": {"d sa", "iso", "ore", "sor", "vi"},
	"void axe": {"id a", "oid", "voi"},
	"void sceptre": {"id s", "oid", "voi"},
	"war buckler": {"ar bu"},
	"war hammer": {"ar h"},
	"war sword": {"ar sw"},
	"whalebone rapier": {"eb", "hal"},
	"widowsilk robe": {"dow", "ido"},
	"wild leather": {"d le", "wil", "wild"},
	"woodsplitter": {"dsp"},
	"wool gloves": {"ol g", "ool"},
	"wool shoes": {"oe", "ool"},
	"wrapped mitts": {"d mi", "pped m", "wrapped m"},
	"wyrmscale doublet": {"mscale d"},
	"wyrmscale gauntlets": {"mscale g"},
	"zealot gloves": {"ot g", "t gl"},
	"zealot helmet": {"ot h", "t h"},
	"zodiac leather": {"c l"},
}